import datetime

dt_kst = datetime.datetime.utcnow() + datetime.timedelta(hours=9)

YEAR = dt_kst.year

TOPIC_NAME = "RTC_DATA"
BUCKET_NAME = "rtc-raw-data"

DEFAULT_HEADERS = {"Content-Type": "application/json; charset=utf-8"}

# 서울특별시
SEOUL_MUNICIPALITY_CODE = {
    "강남구": 11680,
    "강동구": 11740,
    "강북구": 11305,
    "강서구": 11500,
    "관악구": 11620,
    "광진구": 11215,
    "구로구": 11530,
    "금천구": 11545,
    "노원구": 11350,
    "도봉구": 11320,
    "동대문구": 11230,
    "동작구": 11590,
    "마포구": 11440,
    "서대문구": 11410,
    "서초구": 11650,
    "성동구": 11200,
    "성북구": 11290,
    "송파구": 11710,
    "양천구": 11470,
    "영등포구": 11560,
    "용산구": 11170,
    "은평구": 11380,
    "종로구": 11110,
    "중구": 11140,
    "중랑구": 11260,
}


DATA_GO_KR_API_KEYS = {
    # 소상공인시장진흥공단_서울 개업 현황
    1: "15069600/v1/uddi:2d1c3fef-b3c7-46b2-8e47-9fcc6ff74faa",
    # 소상공인시장진흥공단_상가(상권)정보
    # 서울특별시 자치구별 상권분석 정보(2017)
    2: "15083033/v1/uddi:324125cb-6185-41a8-9480-8be3a8e4a717",
    # 상권정보업종 코드집(2015년 12월)
    3: "15083033/v1/uddi:7cd9627d-c3c4-4688-8924-d49466c8c4ef_201805091704",
}


SEOUL_DATA_API_KEYS = {
    # https://data.seoul.go.kr/dataList/OA-15568/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-생활인구)
    1: "VwsmTrdarFlpopQq",
    # https://data.seoul.go.kr/dataList/OA-15569/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-직장인구)
    2: "VwsmTrdarWrcPopltnQq",
    # http://data.seoul.go.kr/dataList/OA-15582/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권배후지-생활인구)
    3: "VwsmTrdhlFlpopQq",
    # https://data.seoul.go.kr/dataList/OA-15570/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권배후지-직장인구)
    4: "Vwsm_TrdhlWrcPopltnQq",
    # https://data.seoul.go.kr/dataList/OA-15584/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권_상주인구)
    5: "VwsmTrdarRepopQq",
    # https://data.seoul.go.kr/dataList/OA-21278/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-소득소비)
    6: "trdarNcmCnsmp",
    # http://data.seoul.go.kr/dataList/OA-15572/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-추정매출)
    7: "VwsmTrdarSelngQq",
    # https://data.seoul.go.kr/dataList/OA-15573/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권배후지-추정매출)
    8: "VwsmTrdhlSelngQq",
    # https://data.seoul.go.kr/dataList/OA-15560/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권영역)
    9: "TbgisTrdarRelm",
    # https://data.seoul.go.kr/dataList/OA-15566/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-아파트)
    10: "InfoTrdarAptQq",
    # https://data.seoul.go.kr/dataList/OA-15574/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권배후지-아파트)
    11: "VwsmTrdhlAptQq",
    # https://data.seoul.go.kr/dataList/OA-15567/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(자치구별 상권변화지표)
    12: "VwsmSignguIxQq",
    # https://data.seoul.go.kr/dataList/OA-15575/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(행정동별 상권변화지표)
    13: "VwsmAdstrdIxQq",
    # https://data.seoul.go.kr/dataList/OA-15576/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-상권변화지표)
    14: "VwsmTrdarIxQq",
    # https://data.seoul.go.kr/dataList/OA-15577/S/1/datasetView.do
    # 서울시 우리마을가게 상권분석서비스(상권-점포)
    15: "VwsmTrdarStorQq",
    # https://data.seoul.go.kr/dataList/OA-20471/S/1/datasetView.do
    # 서울시 불법주정차/전용차로 위반 단속 CCTV 위치정보
    16: "TbOpendataFixedcctv",
    # https://data.seoul.go.kr/dataList/OA-13122/S/1/datasetView.do
    # 서울시 공영주차장 안내 정보
    17: "GetParkInfo",
    # http://data.seoul.go.kr/dataList/OA-15410/S/1/datasetView.do
    # 서울시 건축물대장 법정동 코드정보
    18: "bigCmpBjdongMgmInfo",
}

# 상업 분류 참고

"""
LARGEUPJONG = [
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "공공·국방·사회보장", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "N", "indsLclsNm": "관광/여가/오락", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "교육", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "T", "indsLclsNm": "복지", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "스포츠", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "9", "indsLclsNm": "업종분류불능", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "9", "indsLclsNm": "업종분류불능", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "운수·창고", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "전기/가스/수도", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "전자/정보통신", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "J", "indsLclsNm": "정보통신업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "stdrDt": "2015-12-17"},
]

MIDDLEUPJONG = [
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A09", "indsMclsNm": "광업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A01", "indsMclsNm": "농업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A01", "indsMclsNm": "농업/축산", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A03", "indsMclsNm": "농업관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A07", "indsMclsNm": "양식업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A06", "indsMclsNm": "어업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A03", "indsMclsNm": "어업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A02", "indsMclsNm": "임업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A05", "indsMclsNm": "임업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A02", "indsMclsNm": "조경", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "1차산업", "indsMclsCd": "A04", "indsMclsNm": "축산/수렵서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F03", "indsMclsNm": "개인/가정용품수리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F11", "indsMclsNm": "개인서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F12", "indsMclsNm": "광고/인쇄", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F13", "indsMclsNm": "기타서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F09", "indsMclsNm": "대중목욕탕/휴게", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F08", "indsMclsNm": "대행업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F07", "indsMclsNm": "물품기기대여", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F19", "indsMclsNm": "법무세무회계", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F06", "indsMclsNm": "사진", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F02", "indsMclsNm": "세탁/가사서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F17", "indsMclsNm": "예식/의례/관혼상제", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F04", "indsMclsNm": "운송/배달/택배", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F01", "indsMclsNm": "이/미용/건강", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F05", "indsMclsNm": "인력/고용/용역알선", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F14", "indsMclsNm": "자동차/이륜차", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F18", "indsMclsNm": "장례/묘지", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F42", "indsMclsNm": "전문직별 공사업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F41", "indsMclsNm": "종합 건설업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F16", "indsMclsNm": "주유소/충전소", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F15", "indsMclsNm": "주택수리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "건설업", "indsMclsCd": "F20", "indsMclsNm": "행사/이벤트", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "O",
        "indsLclsNm": "공공·국방·사회보장",
        "indsMclsCd": "O84",
        "indsMclsNm": "공공 행정, 국방 및 사회보장 행정",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "O",
        "indsLclsNm": "공공·국방·사회보장",
        "indsMclsCd": "O02",
        "indsMclsNm": "모텔/여관/여인숙",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "O", "indsLclsNm": "공공·국방·사회보장", "indsMclsCd": "O05", "indsMclsNm": "민박/하숙", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "공공·국방·사회보장", "indsMclsCd": "O04", "indsMclsNm": "유스호스텔", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "O",
        "indsLclsNm": "공공·국방·사회보장",
        "indsMclsCd": "O03",
        "indsMclsNm": "캠프/별장/펜션",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "O", "indsLclsNm": "공공·국방·사회보장", "indsMclsCd": "O01", "indsMclsNm": "호텔/콘도", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "M",
        "indsLclsNm": "과학·기술",
        "indsMclsCd": "M73",
        "indsMclsNm": "기타 전문, 과학 및 기술 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M05", "indsMclsNm": "기타교육문화기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M70", "indsMclsNm": "연구개발업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M04", "indsMclsNm": "연극/음악", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M02", "indsMclsNm": "영화제작/배급", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M72", "indsMclsNm": "전문 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M71", "indsMclsNm": "전문 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "과학·기술", "indsMclsCd": "M01", "indsMclsNm": "종교", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N01",
        "indsMclsNm": "PC/오락/당구/볼링등",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N08",
        "indsMclsNm": "경마/경륜/성인오락",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N07",
        "indsMclsNm": "놀이/여가/취미",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N02",
        "indsMclsNm": "무도/유흥/가무",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N75",
        "indsMclsNm": "사업 지원 서비스업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N74",
        "indsMclsNm": "사업시설 관리 및 조경 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "N", "indsLclsNm": "관광/여가/오락", "indsMclsCd": "N04", "indsMclsNm": "스포츠/운동", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N03",
        "indsMclsNm": "연극/영화/극장",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N05",
        "indsMclsNm": "요가/단전/마사지",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "관광/여가/오락",
        "indsMclsCd": "N76",
        "indsMclsNm": "임대업; 부동산 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "N", "indsLclsNm": "관광/여가/오락", "indsMclsCd": "N06", "indsMclsNm": "전시/관람", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B04", "indsMclsNm": "가방/가죽제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B23", "indsMclsNm": "건설/건축자재제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B12", "indsMclsNm": "고무/플라스틱제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B08", "indsMclsNm": "광업 지원 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B14", "indsMclsNm": "귀금속/장신구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B06", "indsMclsNm": "금속 광업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B26", "indsMclsNm": "기계/장비/기구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B06", "indsMclsNm": "모피제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B07", "indsMclsNm": "목재/가구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B17", "indsMclsNm": "문구/잡화제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B18", "indsMclsNm": "방적/방직/직물제조", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "B",
        "indsLclsNm": "광업",
        "indsMclsCd": "B07",
        "indsMclsNm": "비금속광물 광업; 연료용 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B21", "indsMclsNm": "석유화합물/연료제조", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "B",
        "indsLclsNm": "광업",
        "indsMclsCd": "B05",
        "indsMclsNm": "석탄, 원유 및 천연가스 광업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B02", "indsMclsNm": "섬유/직물제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B01", "indsMclsNm": "식품가공/제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B05", "indsMclsNm": "신발제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B15", "indsMclsNm": "악기제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B16", "indsMclsNm": "운동용품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B13", "indsMclsNm": "유리/도자기제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B03", "indsMclsNm": "의복제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B09", "indsMclsNm": "인쇄", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B25", "indsMclsNm": "재생가공처리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B22", "indsMclsNm": "전자부품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B11", "indsMclsNm": "제약업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B24", "indsMclsNm": "제철/제련/금속처리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B08", "indsMclsNm": "종이류제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "광업", "indsMclsCd": "B10", "indsMclsNm": "화합물/화학제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "교육", "indsMclsCd": "P85", "indsMclsNm": "교육 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "교육", "indsMclsCd": "P02", "indsMclsNm": "실내운동시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "교육", "indsMclsCd": "P03", "indsMclsNm": "실외운동시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "교육", "indsMclsCd": "P01", "indsMclsNm": "운영관리시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G14", "indsMclsNm": "관광서비스", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "G",
        "indsLclsNm": "교통/운송",
        "indsMclsCd": "G46",
        "indsMclsNm": "도매 및 상품 중개업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G02", "indsMclsNm": "버스운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G06", "indsMclsNm": "선박/해운", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "G",
        "indsLclsNm": "교통/운송",
        "indsMclsCd": "G47",
        "indsMclsNm": "소매업; 자동차 제외",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "G",
        "indsLclsNm": "교통/운송",
        "indsMclsCd": "G09",
        "indsMclsNm": "역/터미널/자동차시설",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G12", "indsMclsNm": "운송중개/대행서비스", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "G",
        "indsLclsNm": "교통/운송",
        "indsMclsCd": "G45",
        "indsMclsNm": "자동차 및 부품 판매업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G04", "indsMclsNm": "자동차/이륜차", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G01", "indsMclsNm": "철도운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G03", "indsMclsNm": "택시운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G07", "indsMclsNm": "항공", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G10", "indsMclsNm": "항구/선박시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G05", "indsMclsNm": "화물운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "교통/운송", "indsMclsCd": "G08", "indsMclsNm": "화물취급/보관창고", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V18", "indsMclsNm": "국가/공공서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V13", "indsMclsNm": "국방/병무", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V09", "indsMclsNm": "농수산행정", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V16", "indsMclsNm": "단체", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V06", "indsMclsNm": "문화관련국가기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V14", "indsMclsNm": "법무/치안", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V04", "indsMclsNm": "보조행정기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V15", "indsMclsNm": "사법기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V07", "indsMclsNm": "사회보장국가기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V08", "indsMclsNm": "산업진흥행정", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V11", "indsMclsNm": "외교", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V10", "indsMclsNm": "운수/통신행정", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V01", "indsMclsNm": "입법기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V02", "indsMclsNm": "중앙행정기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V03", "indsMclsNm": "지방행정기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "V", "indsLclsNm": "국가기관/단체", "indsMclsCd": "V05", "indsMclsNm": "학술관련기관", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "K",
        "indsLclsNm": "금융",
        "indsMclsCd": "K66",
        "indsMclsNm": "금융 및 보험관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K05", "indsMclsNm": "금융관련단체/기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K64", "indsMclsNm": "금융업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K04", "indsMclsNm": "기타금융", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K03", "indsMclsNm": "보험", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K65", "indsMclsNm": "보험 및 연금업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K01", "indsMclsNm": "은행", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융", "indsMclsCd": "K02", "indsMclsNm": "증권", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "K",
        "indsLclsNm": "금융·보험",
        "indsMclsCd": "K66",
        "indsMclsNm": "금융 및 보험관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K05", "indsMclsNm": "금융관련단체/기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K64", "indsMclsNm": "금융업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K04", "indsMclsNm": "기타금융", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K03", "indsMclsNm": "보험", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K65", "indsMclsNm": "보험 및 연금업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K01", "indsMclsNm": "은행", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "K", "indsLclsNm": "금융·보험", "indsMclsCd": "K02", "indsMclsNm": "증권", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I01", "indsMclsNm": "건설업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "I",
        "indsLclsNm": "기술/건축/환경",
        "indsMclsCd": "I04",
        "indsMclsNm": "건축/엔지니어링/기술서비스",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "I",
        "indsLclsNm": "기술/건축/환경",
        "indsMclsCd": "I02",
        "indsMclsNm": "건축설비/설치공사",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I05", "indsMclsNm": "검사/감리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I08", "indsMclsNm": "기계장비임대", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I55", "indsMclsNm": "숙박업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "I",
        "indsLclsNm": "기술/건축/환경",
        "indsMclsCd": "I56",
        "indsMclsNm": "음식점 및 주점업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I09", "indsMclsNm": "중장비", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "I",
        "indsLclsNm": "기술/건축/환경",
        "indsMclsCd": "I06",
        "indsMclsNm": "폐기물/재활용품",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "I", "indsLclsNm": "기술/건축/환경", "indsMclsCd": "I07", "indsMclsNm": "환경관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A09", "indsMclsNm": "광업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A01", "indsMclsNm": "농업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A01", "indsMclsNm": "농업/축산", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A03", "indsMclsNm": "농업관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A07", "indsMclsNm": "양식업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A06", "indsMclsNm": "어업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A03", "indsMclsNm": "어업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A02", "indsMclsNm": "임업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A05", "indsMclsNm": "임업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "A", "indsLclsNm": "농업·임업·어업", "indsMclsCd": "A02", "indsMclsNm": "조경", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "A",
        "indsLclsNm": "농업·임업·어업",
        "indsMclsCd": "A04",
        "indsMclsNm": "축산/수렵서비스",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G14", "indsMclsNm": "관광서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G46", "indsMclsNm": "도매 및 상품 중개업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G02", "indsMclsNm": "버스운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G06", "indsMclsNm": "선박/해운", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G47", "indsMclsNm": "소매업; 자동차 제외", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G09", "indsMclsNm": "역/터미널/자동차시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G12", "indsMclsNm": "운송중개/대행서비스", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "G",
        "indsLclsNm": "도·소매",
        "indsMclsCd": "G45",
        "indsMclsNm": "자동차 및 부품 판매업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G04", "indsMclsNm": "자동차/이륜차", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G01", "indsMclsNm": "철도운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G03", "indsMclsNm": "택시운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G07", "indsMclsNm": "항공", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G10", "indsMclsNm": "항구/선박시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G05", "indsMclsNm": "화물운송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "G", "indsLclsNm": "도·소매", "indsMclsCd": "G08", "indsMclsNm": "화물취급/보관창고", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C24",
        "indsMclsNm": "1차 금속 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C09", "indsMclsNm": "가공식품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C32", "indsMclsNm": "가구 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C15", "indsMclsNm": "가구도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C16", "indsMclsNm": "가전제품도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C15",
        "indsMclsNm": "가죽, 가방 및 신발 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C14",
        "indsMclsNm": "가죽/모피제품도매",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C32",
        "indsMclsNm": "건축관련자재도매",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C22",
        "indsMclsNm": "고무 및 플라스틱제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C36",
        "indsMclsNm": "고무/플라스틱류도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C01", "indsMclsNm": "곡물/종자도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C25",
        "indsMclsNm": "금속 가공제품 제조업; 기계 및 가구 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C38", "indsMclsNm": "기계장비도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C29",
        "indsMclsNm": "기타 기계 및 장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C31",
        "indsMclsNm": "기타 운송장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C33",
        "indsMclsNm": "기타 제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C20",
        "indsMclsNm": "기타생활용품도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C41", "indsMclsNm": "기타유통관련업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C12", "indsMclsNm": "담배 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C34", "indsMclsNm": "도료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C05", "indsMclsNm": "동물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C16",
        "indsMclsNm": "목재 및 나무제품 제조업; 가구 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C31", "indsMclsNm": "목재도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C39", "indsMclsNm": "무역업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C23",
        "indsMclsNm": "비금속 광물제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C02", "indsMclsNm": "사료도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C25",
        "indsMclsNm": "사진/광학/정밀기기도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C40", "indsMclsNm": "상품중개", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C24",
        "indsMclsNm": "서적/음반/문구도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C11", "indsMclsNm": "섬유/직물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C13",
        "indsMclsNm": "섬유제품 제조업; 의복 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C07", "indsMclsNm": "수산물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C27",
        "indsMclsNm": "시계/귀금속도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C10", "indsMclsNm": "식료품 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C13", "indsMclsNm": "신발도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C29", "indsMclsNm": "연료도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C19",
        "indsMclsNm": "요업/목제품도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C28", "indsMclsNm": "운동용품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C33", "indsMclsNm": "유리도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C11", "indsMclsNm": "음료 제조업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C27",
        "indsMclsNm": "의료, 정밀, 광학 기기 및 시계 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C21",
        "indsMclsNm": "의료용 물질 및 의약품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C12", "indsMclsNm": "의류도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C14",
        "indsMclsNm": "의복, 의복 액세서리 및 모피제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C21",
        "indsMclsNm": "의약/의료품도매",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C18",
        "indsMclsNm": "인쇄 및 기록매체 복제업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C30",
        "indsMclsNm": "자동차 및 트레일러 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C08", "indsMclsNm": "자연산원료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C18", "indsMclsNm": "장식재도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C37", "indsMclsNm": "재료도매/수집", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C28",
        "indsMclsNm": "전기장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C26",
        "indsMclsNm": "전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C23", "indsMclsNm": "종이류도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C10",
        "indsMclsNm": "주류/기호품도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C17", "indsMclsNm": "주방용품도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C30",
        "indsMclsNm": "철근/금속재도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C04", "indsMclsNm": "청과물도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C06", "indsMclsNm": "축산물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C26",
        "indsMclsNm": "취미/오락용품도매",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C19",
        "indsMclsNm": "코크스, 연탄 및 석유정제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C17",
        "indsMclsNm": "펄프, 종이 및 종이제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C22",
        "indsMclsNm": "화장품/비누/세정제도매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "도매/유통/무역", "indsMclsCd": "C03", "indsMclsNm": "화초/식물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C20",
        "indsMclsNm": "화학 물질 및 화학제품 제조업; 의약품 제외",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "도매/유통/무역",
        "indsMclsCd": "C35",
        "indsMclsNm": "화합물/화학제품도매",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "M",
        "indsLclsNm": "문화/예술/종교",
        "indsMclsCd": "M73",
        "indsMclsNm": "기타 전문, 과학 및 기술 서비스업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "M",
        "indsLclsNm": "문화/예술/종교",
        "indsMclsCd": "M05",
        "indsMclsNm": "기타교육문화기관",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M70", "indsMclsNm": "연구개발업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M04", "indsMclsNm": "연극/음악", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M02", "indsMclsNm": "영화제작/배급", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M71", "indsMclsNm": "전문 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M72", "indsMclsNm": "전문 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "M", "indsLclsNm": "문화/예술/종교", "indsMclsCd": "M01", "indsMclsNm": "종교", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q14", "indsMclsNm": "기타음식업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q05", "indsMclsNm": "닭/오리요리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q10", "indsMclsNm": "별식/퓨전요리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q86", "indsMclsNm": "보건업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q87", "indsMclsNm": "보건업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q15", "indsMclsNm": "부페", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q04", "indsMclsNm": "분식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q06", "indsMclsNm": "양식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q09", "indsMclsNm": "유흥주점", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q13", "indsMclsNm": "음식배달서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q03", "indsMclsNm": "일식/수산물", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q08", "indsMclsNm": "제과제빵떡케익", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q02", "indsMclsNm": "중식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q12", "indsMclsNm": "커피점/카페", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q07", "indsMclsNm": "패스트푸드", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "보건", "indsMclsCd": "Q01", "indsMclsNm": "한식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L05", "indsMclsNm": "부동산관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L05", "indsMclsNm": "부동산관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L68", "indsMclsNm": "부동산업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L68", "indsMclsNm": "부동산업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L02", "indsMclsNm": "부동산임대", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L02", "indsMclsNm": "부동산임대", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L01", "indsMclsNm": "부동산중개", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L01", "indsMclsNm": "부동산중개", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L03", "indsMclsNm": "분양", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L03", "indsMclsNm": "분양", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L04", "indsMclsNm": "평가/개발/관리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "L", "indsLclsNm": "부동산", "indsMclsCd": "L04", "indsMclsNm": "평가/개발/관리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F03", "indsMclsNm": "개인/가정용품수리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F11", "indsMclsNm": "개인서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F12", "indsMclsNm": "광고/인쇄", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F13", "indsMclsNm": "기타서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F09", "indsMclsNm": "대중목욕탕/휴게", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F08", "indsMclsNm": "대행업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F07", "indsMclsNm": "물품기기대여", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F19", "indsMclsNm": "법무세무회계", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F06", "indsMclsNm": "사진", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F02", "indsMclsNm": "세탁/가사서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F17", "indsMclsNm": "예식/의례/관혼상제", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F04", "indsMclsNm": "운송/배달/택배", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F01", "indsMclsNm": "이/미용/건강", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F05", "indsMclsNm": "인력/고용/용역알선", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F14", "indsMclsNm": "자동차/이륜차", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F18", "indsMclsNm": "장례/묘지", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F42", "indsMclsNm": "전문직별 공사업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F41", "indsMclsNm": "종합 건설업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F16", "indsMclsNm": "주유소/충전소", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F15", "indsMclsNm": "주택수리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "F", "indsLclsNm": "생활서비스", "indsMclsCd": "F20", "indsMclsNm": "행사/이벤트", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D15", "indsMclsNm": "가구소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D06", "indsMclsNm": "가방/신발/액세서리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D12", "indsMclsNm": "가전제품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D07", "indsMclsNm": "가정/주방/인테리어", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D10", "indsMclsNm": "건강/미용식품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D25", "indsMclsNm": "기타판매업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D08", "indsMclsNm": "사무/문구/컴퓨터", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D18", "indsMclsNm": "사진/광학/정밀기기소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D02", "indsMclsNm": "선물/팬시/기념품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D26", "indsMclsNm": "시계/귀금속소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D09", "indsMclsNm": "애견/애완/동물", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D17", "indsMclsNm": "예술품/골동품/수석/분재", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D14", "indsMclsNm": "운동/경기용품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D11", "indsMclsNm": "유아용품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D01", "indsMclsNm": "음/식료품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D05", "indsMclsNm": "의복의류", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D20", "indsMclsNm": "의약/의료품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D23", "indsMclsNm": "자동차/자동차용품", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "D",
        "indsLclsNm": "소매",
        "indsMclsCd": "D35",
        "indsMclsNm": "전기, 가스, 증기 및 공기 조절 공급업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D19", "indsMclsNm": "종교용품판매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D03", "indsMclsNm": "종합소매점", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D24", "indsMclsNm": "중고품소매/교환", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D13", "indsMclsNm": "책/서적/도서", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D21", "indsMclsNm": "철물/난방/건설자재소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D04", "indsMclsNm": "취미/오락관련소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D22", "indsMclsNm": "페인트/유리제품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "소매", "indsMclsCd": "D16", "indsMclsNm": "화장품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "indsMclsCd": "E02", "indsMclsNm": "가스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "indsMclsCd": "E04", "indsMclsNm": "수도", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "indsMclsCd": "E36", "indsMclsNm": "수도업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "indsMclsCd": "E01", "indsMclsNm": "전기", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "수도·하수", "indsMclsCd": "E03", "indsMclsNm": "증기/온수/기타", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "E",
        "indsLclsNm": "수도·하수",
        "indsMclsCd": "E38",
        "indsMclsNm": "폐기물 수집, 운반, 처리 및 원료 재생업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "E",
        "indsLclsNm": "수도·하수",
        "indsMclsCd": "E37",
        "indsMclsNm": "하수, 폐수 및 분뇨 처리업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "E",
        "indsLclsNm": "수도·하수",
        "indsMclsCd": "E39",
        "indsMclsNm": "환경 정화 및 복원업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "S",
        "indsLclsNm": "수리·개인서비스",
        "indsMclsCd": "S95",
        "indsMclsNm": "개인 및 소비용품 수리업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "S",
        "indsLclsNm": "수리·개인서비스",
        "indsMclsCd": "S96",
        "indsMclsNm": "기타 개인 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S01", "indsMclsNm": "병원", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S06", "indsMclsNm": "비수용복지시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S05", "indsMclsNm": "수용복지시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S04", "indsMclsNm": "수의업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S02", "indsMclsNm": "약국/한약방", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S03", "indsMclsNm": "유사의료업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "S",
        "indsLclsNm": "수리·개인서비스",
        "indsMclsCd": "S07",
        "indsMclsNm": "의료관련서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "S", "indsLclsNm": "수리·개인서비스", "indsMclsCd": "S94", "indsMclsNm": "협회 및 단체", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "O",
        "indsLclsNm": "숙박",
        "indsMclsCd": "O84",
        "indsMclsNm": "공공 행정, 국방 및 사회보장 행정",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "indsMclsCd": "O02", "indsMclsNm": "모텔/여관/여인숙", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "indsMclsCd": "O05", "indsMclsNm": "민박/하숙", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "indsMclsCd": "O04", "indsMclsNm": "유스호스텔", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "indsMclsCd": "O03", "indsMclsNm": "캠프/별장/펜션", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "O", "indsLclsNm": "숙박", "indsMclsCd": "O01", "indsMclsNm": "호텔/콘도", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I01", "indsMclsNm": "건설업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "I",
        "indsLclsNm": "숙박·음식",
        "indsMclsCd": "I04",
        "indsMclsNm": "건축/엔지니어링/기술서비스",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I02", "indsMclsNm": "건축설비/설치공사", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I05", "indsMclsNm": "검사/감리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I08", "indsMclsNm": "기계장비임대", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I55", "indsMclsNm": "숙박업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I56", "indsMclsNm": "음식점 및 주점업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I09", "indsMclsNm": "중장비", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I06", "indsMclsNm": "폐기물/재활용품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "I", "indsLclsNm": "숙박·음식", "indsMclsCd": "I07", "indsMclsNm": "환경관련서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "스포츠", "indsMclsCd": "P85", "indsMclsNm": "교육 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "스포츠", "indsMclsCd": "P02", "indsMclsNm": "실내운동시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "스포츠", "indsMclsCd": "P03", "indsMclsNm": "실외운동시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "P", "indsLclsNm": "스포츠", "indsMclsCd": "P01", "indsMclsNm": "운영관리시설", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N01",
        "indsMclsNm": "PC/오락/당구/볼링등",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N08",
        "indsMclsNm": "경마/경륜/성인오락",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "indsMclsCd": "N07", "indsMclsNm": "놀이/여가/취미", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "indsMclsCd": "N02", "indsMclsNm": "무도/유흥/가무", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N75",
        "indsMclsNm": "사업 지원 서비스업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N74",
        "indsMclsNm": "사업시설 관리 및 조경 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "indsMclsCd": "N04", "indsMclsNm": "스포츠/운동", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "indsMclsCd": "N03", "indsMclsNm": "연극/영화/극장", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N05",
        "indsMclsNm": "요가/단전/마사지",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "N",
        "indsLclsNm": "시설관리·임대",
        "indsMclsCd": "N76",
        "indsMclsNm": "임대업; 부동산 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "N", "indsLclsNm": "시설관리·임대", "indsMclsCd": "N06", "indsMclsNm": "전시/관람", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U01", "indsMclsNm": "TV", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U05", "indsMclsNm": "광고", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U08", "indsMclsNm": "도서출판", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U02", "indsMclsNm": "라디오", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U09", "indsMclsNm": "멀티미디어", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U04", "indsMclsNm": "방송제작", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U10", "indsMclsNm": "시장/여론조사", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U07", "indsMclsNm": "신문", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U03", "indsMclsNm": "유선방송", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "U", "indsLclsNm": "언론/미디어", "indsMclsCd": "U06", "indsMclsNm": "정보제공", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R20", "indsMclsNm": "기타교육기관", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R10",
        "indsMclsNm": "도서관/독서실",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R91",
        "indsMclsNm": "스포츠 및 오락관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R14", "indsMclsNm": "연구소", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R08", "indsMclsNm": "유아교육", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R90",
        "indsMclsNm": "창작, 예술 및 여가관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R12", "indsMclsNm": "특수교육기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R11", "indsMclsNm": "학교", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R13", "indsMclsNm": "학문교육기타", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R01",
        "indsMclsNm": "학원-보습교습입시",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R04", "indsMclsNm": "학원-어학", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R07",
        "indsMclsNm": "학원-예능취미체육",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R05",
        "indsMclsNm": "학원-음악미술무용",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R03",
        "indsMclsNm": "학원-자격/국가고시",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "R",
        "indsLclsNm": "예술·스포츠·여가",
        "indsMclsCd": "R02",
        "indsMclsNm": "학원-창업취업취미",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R06", "indsMclsNm": "학원-컴퓨터", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "예술·스포츠·여가", "indsMclsCd": "R09", "indsMclsNm": "학원기타", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "운수·창고", "indsMclsCd": "H02", "indsMclsNm": "소프트웨어", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "H",
        "indsLclsNm": "운수·창고",
        "indsMclsCd": "H49",
        "indsMclsNm": "육상 운송 및 파이프라인 운송업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "H", "indsLclsNm": "운수·창고", "indsMclsCd": "H04", "indsMclsNm": "인터넷", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "운수·창고", "indsMclsCd": "H03", "indsMclsNm": "정보기술서비스", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "H",
        "indsLclsNm": "운수·창고",
        "indsMclsCd": "H52",
        "indsMclsNm": "창고 및 운송관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "H", "indsLclsNm": "운수·창고", "indsMclsCd": "H01", "indsMclsNm": "통신업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q14", "indsMclsNm": "기타음식업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q05", "indsMclsNm": "닭/오리요리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q10", "indsMclsNm": "별식/퓨전요리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q86", "indsMclsNm": "보건업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q87", "indsMclsNm": "보건업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q15", "indsMclsNm": "부페", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q04", "indsMclsNm": "분식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q06", "indsMclsNm": "양식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q09", "indsMclsNm": "유흥주점", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q13", "indsMclsNm": "음식배달서비스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q03", "indsMclsNm": "일식/수산물", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q08", "indsMclsNm": "제과제빵떡케익", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q02", "indsMclsNm": "중식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q12", "indsMclsNm": "커피점/카페", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q07", "indsMclsNm": "패스트푸드", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "Q", "indsLclsNm": "음식", "indsMclsCd": "Q01", "indsMclsNm": "한식", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S95", "indsMclsNm": "개인 및 소비용품 수리업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S96", "indsMclsNm": "기타 개인 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S01", "indsMclsNm": "병원", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S06", "indsMclsNm": "비수용복지시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S05", "indsMclsNm": "수용복지시설", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S04", "indsMclsNm": "수의업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S02", "indsMclsNm": "약국/한약방", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S03", "indsMclsNm": "유사의료업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S07", "indsMclsNm": "의료관련서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "S", "indsLclsNm": "의료", "indsMclsCd": "S94", "indsMclsNm": "협회 및 단체", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "전기/가스/수도", "indsMclsCd": "E02", "indsMclsNm": "가스", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "전기/가스/수도", "indsMclsCd": "E04", "indsMclsNm": "수도", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "전기/가스/수도", "indsMclsCd": "E36", "indsMclsNm": "수도업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "E", "indsLclsNm": "전기/가스/수도", "indsMclsCd": "E01", "indsMclsNm": "전기", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "E",
        "indsLclsNm": "전기/가스/수도",
        "indsMclsCd": "E03",
        "indsMclsNm": "증기/온수/기타",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "E",
        "indsLclsNm": "전기/가스/수도",
        "indsMclsCd": "E38",
        "indsMclsNm": "폐기물 수집, 운반, 처리 및 원료 재생업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "E",
        "indsLclsNm": "전기/가스/수도",
        "indsMclsCd": "E37",
        "indsMclsNm": "하수, 폐수 및 분뇨 처리업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "E",
        "indsLclsNm": "전기/가스/수도",
        "indsMclsCd": "E39",
        "indsMclsNm": "환경 정화 및 복원업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D15", "indsMclsNm": "가구소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D06", "indsMclsNm": "가방/신발/액세서리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D12", "indsMclsNm": "가전제품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D07", "indsMclsNm": "가정/주방/인테리어", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D10", "indsMclsNm": "건강/미용식품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D25", "indsMclsNm": "기타판매업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D08", "indsMclsNm": "사무/문구/컴퓨터", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "D",
        "indsLclsNm": "전기·가스",
        "indsMclsCd": "D18",
        "indsMclsNm": "사진/광학/정밀기기소매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D02", "indsMclsNm": "선물/팬시/기념품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D26", "indsMclsNm": "시계/귀금속소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D09", "indsMclsNm": "애견/애완/동물", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "D",
        "indsLclsNm": "전기·가스",
        "indsMclsCd": "D17",
        "indsMclsNm": "예술품/골동품/수석/분재",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D14", "indsMclsNm": "운동/경기용품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D11", "indsMclsNm": "유아용품", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D01", "indsMclsNm": "음/식료품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D05", "indsMclsNm": "의복의류", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D20", "indsMclsNm": "의약/의료품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D23", "indsMclsNm": "자동차/자동차용품", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "D",
        "indsLclsNm": "전기·가스",
        "indsMclsCd": "D35",
        "indsMclsNm": "전기, 가스, 증기 및 공기 조절 공급업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D19", "indsMclsNm": "종교용품판매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D03", "indsMclsNm": "종합소매점", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D24", "indsMclsNm": "중고품소매/교환", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D13", "indsMclsNm": "책/서적/도서", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "D",
        "indsLclsNm": "전기·가스",
        "indsMclsCd": "D21",
        "indsMclsNm": "철물/난방/건설자재소매",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D04", "indsMclsNm": "취미/오락관련소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D22", "indsMclsNm": "페인트/유리제품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "D", "indsLclsNm": "전기·가스", "indsMclsCd": "D16", "indsMclsNm": "화장품소매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "전자/정보통신", "indsMclsCd": "H02", "indsMclsNm": "소프트웨어", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "H",
        "indsLclsNm": "전자/정보통신",
        "indsMclsCd": "H49",
        "indsMclsNm": "육상 운송 및 파이프라인 운송업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "H", "indsLclsNm": "전자/정보통신", "indsMclsCd": "H04", "indsMclsNm": "인터넷", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "H", "indsLclsNm": "전자/정보통신", "indsMclsCd": "H03", "indsMclsNm": "정보기술서비스", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "H",
        "indsLclsNm": "전자/정보통신",
        "indsMclsCd": "H52",
        "indsMclsNm": "창고 및 운송관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "H", "indsLclsNm": "전자/정보통신", "indsMclsCd": "H01", "indsMclsNm": "통신업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "J", "indsLclsNm": "정보통신업", "indsMclsCd": "J60", "indsMclsNm": "방송업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "J",
        "indsLclsNm": "정보통신업",
        "indsMclsCd": "J59",
        "indsMclsNm": "영상ㆍ오디오 기록물 제작 및 배급업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "J", "indsLclsNm": "정보통신업", "indsMclsCd": "J61", "indsMclsNm": "우편 및 통신업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "J", "indsLclsNm": "정보통신업", "indsMclsCd": "J63", "indsMclsNm": "정보서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "J", "indsLclsNm": "정보통신업", "indsMclsCd": "J58", "indsMclsNm": "출판업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "J",
        "indsLclsNm": "정보통신업",
        "indsMclsCd": "J62",
        "indsMclsNm": "컴퓨터 프로그래밍, 시스템 통합 및 관리업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B04", "indsMclsNm": "가방/가죽제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B23", "indsMclsNm": "건설/건축자재제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B12", "indsMclsNm": "고무/플라스틱제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B08", "indsMclsNm": "광업 지원 서비스업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B14", "indsMclsNm": "귀금속/장신구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B06", "indsMclsNm": "금속 광업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B26", "indsMclsNm": "기계/장비/기구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B06", "indsMclsNm": "모피제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B07", "indsMclsNm": "목재/가구제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B17", "indsMclsNm": "문구/잡화제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B18", "indsMclsNm": "방적/방직/직물제조", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "B",
        "indsLclsNm": "제조",
        "indsMclsCd": "B07",
        "indsMclsNm": "비금속광물 광업; 연료용 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B21", "indsMclsNm": "석유화합물/연료제조", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "B",
        "indsLclsNm": "제조",
        "indsMclsCd": "B05",
        "indsMclsNm": "석탄, 원유 및 천연가스 광업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B02", "indsMclsNm": "섬유/직물제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B01", "indsMclsNm": "식품가공/제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B05", "indsMclsNm": "신발제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B15", "indsMclsNm": "악기제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B16", "indsMclsNm": "운동용품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B13", "indsMclsNm": "유리/도자기제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B03", "indsMclsNm": "의복제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B09", "indsMclsNm": "인쇄", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B25", "indsMclsNm": "재생가공처리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B22", "indsMclsNm": "전자부품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B11", "indsMclsNm": "제약업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B24", "indsMclsNm": "제철/제련/금속처리", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B08", "indsMclsNm": "종이류제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "B", "indsLclsNm": "제조", "indsMclsCd": "B10", "indsMclsNm": "화합물/화학제품제조", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C24", "indsMclsNm": "1차 금속 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C09", "indsMclsNm": "가공식품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C32", "indsMclsNm": "가구 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C15", "indsMclsNm": "가구도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C16", "indsMclsNm": "가전제품도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C15",
        "indsMclsNm": "가죽, 가방 및 신발 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C14", "indsMclsNm": "가죽/모피제품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C32", "indsMclsNm": "건축관련자재도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C22",
        "indsMclsNm": "고무 및 플라스틱제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C36", "indsMclsNm": "고무/플라스틱류도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C01", "indsMclsNm": "곡물/종자도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C25",
        "indsMclsNm": "금속 가공제품 제조업; 기계 및 가구 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C38", "indsMclsNm": "기계장비도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C29",
        "indsMclsNm": "기타 기계 및 장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C31", "indsMclsNm": "기타 운송장비 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C33", "indsMclsNm": "기타 제품 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C20", "indsMclsNm": "기타생활용품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C41", "indsMclsNm": "기타유통관련업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C12", "indsMclsNm": "담배 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C34", "indsMclsNm": "도료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C05", "indsMclsNm": "동물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C16",
        "indsMclsNm": "목재 및 나무제품 제조업; 가구 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C31", "indsMclsNm": "목재도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C39", "indsMclsNm": "무역업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C23", "indsMclsNm": "비금속 광물제품 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C02", "indsMclsNm": "사료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C25", "indsMclsNm": "사진/광학/정밀기기도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C40", "indsMclsNm": "상품중개", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C24", "indsMclsNm": "서적/음반/문구도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C11", "indsMclsNm": "섬유/직물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C13",
        "indsMclsNm": "섬유제품 제조업; 의복 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C07", "indsMclsNm": "수산물도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C27", "indsMclsNm": "시계/귀금속도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C10", "indsMclsNm": "식료품 제조업", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C13", "indsMclsNm": "신발도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C29", "indsMclsNm": "연료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C19", "indsMclsNm": "요업/목제품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C28", "indsMclsNm": "운동용품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C33", "indsMclsNm": "유리도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C11", "indsMclsNm": "음료 제조업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C27",
        "indsMclsNm": "의료, 정밀, 광학 기기 및 시계 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C21",
        "indsMclsNm": "의료용 물질 및 의약품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C12", "indsMclsNm": "의류도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C14",
        "indsMclsNm": "의복, 의복 액세서리 및 모피제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C21", "indsMclsNm": "의약/의료품도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C18",
        "indsMclsNm": "인쇄 및 기록매체 복제업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C30",
        "indsMclsNm": "자동차 및 트레일러 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C08", "indsMclsNm": "자연산원료도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C18", "indsMclsNm": "장식재도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C37", "indsMclsNm": "재료도매/수집", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C28", "indsMclsNm": "전기장비 제조업", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C26",
        "indsMclsNm": "전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C23", "indsMclsNm": "종이류도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C10", "indsMclsNm": "주류/기호품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C17", "indsMclsNm": "주방용품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C30", "indsMclsNm": "철근/금속재도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C04", "indsMclsNm": "청과물도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C06", "indsMclsNm": "축산물도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C26", "indsMclsNm": "취미/오락용품도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C19",
        "indsMclsNm": "코크스, 연탄 및 석유정제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C17",
        "indsMclsNm": "펄프, 종이 및 종이제품 제조업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C22", "indsMclsNm": "화장품/비누/세정제도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C03", "indsMclsNm": "화초/식물도매", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "C",
        "indsLclsNm": "제조업",
        "indsMclsCd": "C20",
        "indsMclsNm": "화학 물질 및 화학제품 제조업; 의약품 제외",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "C", "indsLclsNm": "제조업", "indsMclsCd": "C35", "indsMclsNm": "화합물/화학제품도매", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R20", "indsMclsNm": "기타교육기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R10", "indsMclsNm": "도서관/독서실", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "학문/교육",
        "indsMclsCd": "R91",
        "indsMclsNm": "스포츠 및 오락관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R14", "indsMclsNm": "연구소", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R08", "indsMclsNm": "유아교육", "stdrDt": "2015-12-17"},
    {
        "indsLclsCd": "R",
        "indsLclsNm": "학문/교육",
        "indsMclsCd": "R90",
        "indsMclsNm": "창작, 예술 및 여가관련 서비스업",
        "stdrDt": "2015-12-17",
    },
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R12", "indsMclsNm": "특수교육기관", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R11", "indsMclsNm": "학교", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R13", "indsMclsNm": "학문교육기타", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R01", "indsMclsNm": "학원-보습교습입시", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R04", "indsMclsNm": "학원-어학", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R07", "indsMclsNm": "학원-예능취미체육", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R05", "indsMclsNm": "학원-음악미술무용", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R03", "indsMclsNm": "학원-자격/국가고시", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R02", "indsMclsNm": "학원-창업취업취미", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R06", "indsMclsNm": "학원-컴퓨터", "stdrDt": "2015-12-17"},
    {"indsLclsCd": "R", "indsLclsNm": "학문/교육", "indsMclsCd": "R09", "indsMclsNm": "학원기타", "stdrDt": "2015-12-17"},
]
"""
